BookingWebApp/Controllers/ApartmentController.cs
using Microsoft.AspNetCore.Mvc;
using Models.Entities;
using Microsoft.Extensions.Configuration;
using Services;
using BookingWebApp.ViewModels;
using DTOs;
using Microsoft.AspNetCore.Authorization;

namespace BookingWebApp.Controllers
{
    public class ApartmentController : Controller
    {
        private readonly ApartmentService _apartmentService;

        public ApartmentController(ApartmentService apartmentService)
        {
            _apartmentService = apartmentService;
        }

        public async Task<IActionResult> ShowApartmentList(int pageIndex = 1, int pageSize = 2)
        {
            var page = await _apartmentService.GetApartmentsAsync(pageIndex, pageSize);

            var vmItems = page.Items.Select(ApartmentViewModel.ConvertToViewModel).ToList();

            var vmPage = PaginatedList<ApartmentViewModel>.Create(vmItems, page.TotalItems, page.PageIndex, page.PageSize);

            return View(vmPage);
        }
        
        public  IActionResult ShowApartmentPage(int id)
        {
            var apt = _apartmentService.GetApartment(id);
            if (apt.Id == 0) return RedirectToAction("ErrorResult");

            var vm = ApartmentViewModel.ConvertToViewModel(apt);

           var reviews = vm.ReviewViewModel.Take(2).ToList();

           vm.ReviewViewModel = reviews;

            if (reviews.Count == 1) vm.ReviewsCount = vm.ReviewsCount;
            else vm.ReviewsCount -= reviews.Count;
            
            return View(vm);
        }

        public async Task<IActionResult> Reviews(int id, int pageIndex = 1, int pageSize = 2)
        {
            var apt = _apartmentService.GetApartment(id);
            if ( apt.Id == 0) return RedirectToAction("ErrorResult");

            var page = await _apartmentService.GetReviewsAsync(id, pageIndex, pageSize);
            var items = page.Items.Select(ReviewViewModel.ConvertToViewModel).ToList();
            var reviewPage = PaginatedList<ReviewViewModel>.Create(items, page.TotalItems, page.PageIndex, page.PageSize);
            var vm = new ReviewsPageViewModel(apt.Id,apt.Name,apt.AvgRating ,apt.ReviewsCount,reviewPage);

            return View("ReviewsList",vm);       
        }

        public IActionResult ErrorResult()
        {
            return View();
        }
    }
}

BookingWebApp/Controllers/CheckOutController.cs
using BookingWebApp.ViewModels;
using Enums;
using Microsoft.AspNetCore.Mvc;
using Models.Entities;
using Services;
using BookingWebApp.Helpers;
using Interfaces.IServices;

namespace BookingWebApp.Controllers
{
    public class CheckOutController : Controller
    {
        private readonly CheckOutService _checkoutService;
        private readonly UserService _userService;
        private readonly ApartmentService _apartmentService;
        private readonly IReviewService _reviewService;
        private readonly AccountHolderService _accountHolderService;


        public CheckOutController(CheckOutService checkOutService, UserService userService,ApartmentService apartmentService, IReviewService reviewService,AccountHolderService accountHolderService)
        {
            _checkoutService = checkOutService;
            _userService = userService;
            _apartmentService = apartmentService;
            _reviewService = reviewService;
            _accountHolderService = accountHolderService;   
        }
        public IActionResult CheckoutReminder(string action)
        {
            int? userId = HttpContext.Session.GetInt32("UserId");
            var user = _userService.GetUser(userId.Value);
            IndexViewModel viewModel = new IndexViewModel
            {
                UserViewModel = UserViewModel.ConvertToViewModel(user)
            };

            if (action == "dismiss")
            {
                ViewBag.ShowCheckOutModal = true;
            }

            return View("~/Views/Home/Index.cshtml", viewModel);

        }

        public IActionResult CheckOutForm()
        {
            int? userId = HttpContext.Session.GetInt32("UserId");
            var booking = HttpContext.Session.GetString("booking");
            BookingViewModel bookingViewModel = BookingViewModelHelper.ReadModelBooking(booking);
            Apartment apartment = _apartmentService.GetApartment(bookingViewModel.ApartmentId);
            bookingViewModel.ApartmentViewModel = ApartmentViewModel.ConvertToViewModel(apartment);

            var checkInDay = bookingViewModel.CheckInDate.Day;
            var checkOutDay = bookingViewModel.CheckOutDate.Day;

            var totalNight = checkOutDay - checkInDay;

            CheckOutViewModel viewModel = new CheckOutViewModel
            {
                BookingViewModel = bookingViewModel,
                TotalNights = totalNight,
            };

            return View(viewModel);
        }
        public IActionResult CheckOut(CheckOutFormViewModel viewModel, ReviewViewModel reviewViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(viewModel);
            }
            
            int? userId = HttpContext.Session.GetInt32("UserId");
            var booking = HttpContext.Session.GetString("booking");
            var account = _accountHolderService.GetAccountHolderById(userId.Value);
            BookingViewModel bookingViewModel = BookingViewModelHelper.ReadModelBooking(booking);
            Apartment apartment = _apartmentService.GetApartment(bookingViewModel.ApartmentId);
            
            _checkoutService.ProcessCheckOut(bookingViewModel.Id);

            if (viewModel.SkipReview != true)
            {
                var reviewModel = ReviewViewModel.ConvertToEntity(reviewViewModel, account); // need to convert back to entity to save back to the database.
                _reviewService.SaveReview(apartment.Id, reviewModel);
            }
            
            HttpContext.Session.Remove("HasCheckOutToday");
            
            return RedirectToAction("Index", "Home");
        }
        
        
        
    }
}

BookingWebApp/Controllers/HomeController.cs
using System.Diagnostics;
using System.Security.Claims;
using Models.Entities;
using Microsoft.AspNetCore.Mvc;
using Services;
using BookingWebApp.ViewModels;
using BookingWebApp.Helpers;
using BookingWebApp.Hub;
using Enums;
using Interfaces.IServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.SignalR;

namespace BookingWebApp.Controllers
{
    
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly BookingService _bookingService;
        private readonly UserService _userService;
        private readonly IReviewService _reviewService;
        private readonly ChatService _chatService;
        private readonly IHubContext<ChatHub> _hubContext;

        public HomeController(ILogger<HomeController> logger,BookingService bookingService, UserService userService, IReviewService reviewService, ChatService chatService,IHubContext<ChatHub>hubContext)
        {
            _logger = logger;
            _bookingService = bookingService;
            _userService = userService;
            _reviewService = reviewService;
            _chatService = chatService;
            _hubContext = hubContext;
        }

      
        public IActionResult Index()
        {
           var reviews =  _reviewService.GetAllReviews(); // this review still need fixing.
            int? userId = HttpContext.Session.GetInt32("UserId");

            if (userId == null)
            {
                IndexViewModel user = new IndexViewModel
                {
                    UserViewModel = new UserViewModel(),
                    BookingViewModel = new List<BookingViewModel>(),
                    ReviewViewModel = ReviewViewModel.ConvertToViewModel(reviews)

                };
                return View(user);
            }
            User userName = _userService.GetUser(userId.Value);
            

            bool hasCheckOuToday = CheckForTodayCheckOut(userId.Value);

            var userBooking = _bookingService.GetAllBookingsForUser(userId.Value);
        
            if (hasCheckOuToday)
            {
                HttpContext.Session.SetInt32("HasCheckOutToday", hasCheckOuToday ? 1 : 0);
                ViewBag.HasCheckOutToday = hasCheckOuToday;
            }

            if (userName.RoleId == 2)
                ViewBag.HostTool = true;
            
            IndexViewModel viewModel = new IndexViewModel
            {
                UserViewModel = UserViewModel.ConvertToViewModel(userName),
                BookingViewModel = BookingViewModelHelper.ConvertToViewModel(userBooking),
                ReviewViewModel = ReviewViewModel.ConvertToViewModel(reviews)
            };

            return View(viewModel);

        }


        public bool CheckForTodayCheckOut(int userId) // will maybe inside a service
        {
            var bookings = _bookingService.GetAllBookingsForUser(userId).FindAll(booking => booking.Status == BookingStatus.Confirmed);

            foreach (var booking in bookings)
            {
                if (booking.CheckOutDate.Date == DateTime.Today) // && confirmed
                {
                    HttpContext.Session.SetString("booking",BookingViewModelHelper.CreateString(booking));
                    return true;
                }
            }
            return false;
        }

        public IActionResult Chat()
        {
            var userId = User.Claims.FirstOrDefault(c => c.Type == "Id");
            int id = userId != null ? int.Parse(userId.Value) : 0;
            
            if (id == 0) return RedirectToAction("ContactUs", "Home");

            var chatMessages = _chatService.GetAllMessages(id).Select(m => new ChatMessageViewModel
            {
                Message = m.Content,
                TimeSent = m.TimeSent,
            }).ToList();


            return View(chatMessages);
        }

        public IActionResult ContactUs()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BookingWebApp/Views/Home/Chat.cshtml
@model List<ChatMessageViewModel>

<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css" rel="stylesheet">

<style>
	.chat-container {
		height: calc(100vh - 70px);
	}

	.chat-messages {
		overflow-y: auto;
		max-height: calc(100vh - 200px);
	}

	#messageInput {
		height: 50px;
	}
</style>
<div class="container-fluid chat-container mt-2">
<div class="row h-100">

	<div class="col-md-9 col-12 p-0 d-flex flex-column">
		<div class="chat-messages p-3 flex-grow-1 overflow-auto" id="messagesList">
			@foreach (var msg in Model)
			{

				<div class="message mb-3">
					<div class=" rounded p-2">
						@msg.Message
					</div>
					<small class="text-muted">@msg.TimeSent</small>
				</div>
			}
		</div>
			<div class="input-group">
				<input type="text" id="messageInput" class="form-control" placeholder="Type a message..." />
				<button class="btn btn-primary" type="button" id="sendButton">
					<i class="bi bi-send"></i> Send
				</button>
			</div>
		</div>
	</div>
</div>
<script src="~/js/signalr/dist/browser/signalr.js"></script>
<script src="~/js/chat.js"></script>
<script>
	function scrollToBottom() {
		const messagesList = document.getElementById('messagesList');
		messagesList.scrollTop = messagesList.scrollHeight;
	}


	document.addEventListener('DOMContentLoaded', function() {
		scrollToBottom();
	});


	document.getElementById('sendButton').addEventListener('click', function() {
		setTimeout(scrollToBottom, 100);
	});

	document.getElementById('messageInput').addEventListener('keypress', function(e) {
		if (e.key === 'Enter') {
			setTimeout(scrollToBottom, 100);
		}
	});
</script>

BookingWebApp/Views/Home/ContactUs.cshtml
<style>
	body {
		background-color: #f8f9fa;
		color: #333;
	}

	.contact-form {
		background-color: #ffffff;
		border-radius: 15px;
		box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
		padding: 30px;
		margin-top: 50px;
	}

		.contact-form h2 {
			color: #007bff;
			margin-bottom: 30px;
		}

	.form-control:focus {
		border-color: #007bff;
		box-shadow: 0 0 0 0.2rem rgba(0, 123, 255, 0.25);
	}

	.btn-primary {
		background-color: #007bff;
		border-color: #007bff;
		transition: all 0.3s ease;
	}

		.btn-primary:hover {
			background-color: #0056b3;
			border-color: #0056b3;
		}
</style>

<div class="container">
	<div class="row justify-content-center">
		<div class="col-md-8 col-lg-6">
			<form class="contact-form">
				<h2 class="text-center mb-4">Contact Us</h2>
				<h3>Want to connect directly with the host? Sign up now and start the conversation!</h3>
				<div class="mb-3">
					<label for="name" class="form-label">Name</label>
					<input type="text" class="form-control" id="name" required>
				</div>
				<div class="mb-3">
					<label for="email" class="form-label">Email address</label>
					<input type="email" class="form-control" id="email" required>
				</div>
				<div class="mb-3">
					<label for="subject" class="form-label">Subject</label>
					<input type="text" class="form-control" id="subject" required>
				</div>
				<div class="mb-3">
					<label for="message" class="form-label">Message</label>
					<textarea class="form-control" id="message" rows="5" required></textarea>
				</div>
				<div class="d-grid">
					<button type="submit" class="btn btn-primary btn-lg">Send Message</button>
				</div>
			</form>
		</div>
	</div>
</div>
=

BookingWebApp/Views/Home/Index.cshtml
@model IndexViewModel    
@{
    ViewData["Title"] = "Home";
    bool hasCheckOutToday = ViewBag.HasCheckOutToday ?? false;
}



<section class="bg-light">

	@if (hasCheckOutToday)
	{
        <div class="container mt-3 position-sticky" style="top: 0; z-index: 1030;">
			<div class="alert alert-warning alert-dismissible fade show" role="alert">
				<strong>Checkout Reminder!</strong> Checkout for booking @Model.CurrentBooking.Id is scheduled for today at @Model.CurrentBooking.ApartmentViewModel.Name.
                <form asp-controller="CheckOut" asp-action="CheckoutReminder" method="post" class="d-inline">
					<a asp-controller="CheckOut" asp-action="CheckOutForm" type="submit" name="action" value="checkout" class="btn btn-danger btn-sm ms-2">
						Checkout Now
					</a>
					<button type="submit" name="action" value="dismiss" class="btn-close" aria-label="Close"></button>
					<p>Number of checkout today : @Model.NumberOfCheckout</p>
				</form>
			</div>
		</div>
	}
    
	<div class="container py-5">
		<div class="row">
			<div class="col-lg-7">
				<h1 class="display-4 fw-bold mb-4">Hello <span id="userName">@Model.UserViewModel.FirstName</span>, welcome to<br>Sun & escape apartment.</h1>
				<p class="lead mb-5">Experience luxury and comfort in the beautiful island of Aruba.</p>
				<div class="d-flex gap-3">
					<a asp-controller="Apartment" asp-action="ShowApartmentList" class="btn btn-dark px-4 py-2">View Apartments</a>
					<a asp-controller="Home" asp-action="Chat" class="btn btn-outline-dark px-4 py-2">Contact Us</a>
				</div>
			</div>
		</div>
	</div>
	<div class="wave-shape">
		<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320">
			<path fill="#12123e" fill-opacity="1" d="M0,96L80,117.3C160,139,320,181,480,186.7C640,192,800,160,960,154.7C1120,149,1280,171,1360,181.3L1440,192L1440,320L1360,320C1280,320,1120,320,960,320C800,320,640,320,480,320C320,320,160,320,80,320L0,320Z"></path>
		</svg>
	</div>
</section>
<section class="bg-primary-custom py-5">
    <div class="container">
        <div id="carouselExampleAutoplaying" class="carousel slide carousel-rounded shadow" data-bs-ride="carousel">
            <div class="carousel-indicators">
                <button type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                <button type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide-to="1" aria-label="Slide 2"></button>
                <button type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide-to="2" aria-label="Slide 3"></button>
            </div>
            <div class="carousel-inner rounded-4">
                <div class="carousel-item active">
                    <img src="~/IMG/apartment.jpg" class="d-block w-100" alt="Apartment view" style="height: 650px; object-fit: cover;">
                </div>
                <div class="carousel-item">
                    <img src="~/IMG/bedView.jpg" class="d-block w-100" alt="Bedroom view" style="height: 650px; object-fit: cover;">
                </div>
                <div class="carousel-item">
                    <img src="~/IMG/apartment.jpg" class="d-block w-100" alt="Apartment exterior" style="height: 650px; object-fit: cover;">
                </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
        </div>
    </div>
</section>
<section class="py-5 bg-light">
    <div class="container py-4">
        <h2 class="display-5 text-center mb-5">About us</h2>
        <div class="row align-items-center">
            <div class="col-lg-6">
                <p class="lead">
                    Our apartments are designed to offer you the sense
                    of comfort that you love to feel at your home.
                    We offer fully equipped apartments in the
                    neighborhood of papaya in Aruba.
                </p>
                <p class="lead">
                    Be it for leisure or for business, we offer you a
                    constant advise and recommendations to enhance
                    your stay and enjoy the beautiful island.
                </p>
                <p class="lead">
                    With their cozy ambiance, tasteful decoration, our
                    apartments and modern swimming pool will be one
                    of your favorite stops in Aruba.
                </p>
            </div>
            <div class="col-lg-6">
                <img src="~/IMG/map.jpg" alt="Location Map" class="img-fluid rounded shadow-sm">
            </div>
        </div>
    </div>
</section>
<section class="py-5">
    <div class="container py-4">
        <div class="row g-4">
            <div class="col-12 col-md-6">
                <div class="p-4 bg-light rounded">
                    <h2 class="display-5 mb-4">Our Apartment</h2>
                </div>
                <div class="mt-4">
                    <img src="~/IMG/bedroom.jpg" class="img-fluid rounded shadow" alt="Bedroom view">
                </div>
            </div>
            <div class="col-12 col-md-6 d-flex flex-column">
                <div class="mb-4">
                    <img src="~/IMG/bedroom-side.jpg" class="img-fluid rounded shadow" alt="Bedroom side view">
                </div>
                <div class="mt-auto">
                    <p class="lead">
                        The apartment is bright and inviting, featuring a palm-lined private pool, cozy seating area, and soft, neutral
                        tones throughout. Stay cool with the in-room A/C, and wind down comfortably in the queen-size bed after a day
                        spent soaking in the warm island sun.
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="py-5 bg-light">
	<div class="container py-4">
		<h2 class="display-5 text-center mb-5">Our Amenities & Facilities</h2>
		<div class="row g-4">
			<div class="col-6 col-md-3">
				<div class="bg-white p-4 text-center rounded shadow-sm h-100">
					<i class="fas fa-swimming-pool fs-1 mb-3" style="color: #12123e;"></i>
					<h5>Swimming Pool</h5>
				</div>
			</div>
			<div class="col-6 col-md-3">
				<div class="bg-white p-4 text-center rounded shadow-sm h-100">
					<i class="fas fa-wifi fs-1 mb-3" style="color: #12123e;"></i>
					<h5>Wifi</h5>
				</div>
			</div>
			<div class="col-6 col-md-3">
				<div class="bg-white p-4 text-center rounded shadow-sm h-100">
					<i class="fas fa-washing-machine fs-1 mb-3" style="color: #12123e;"></i>
					<h5>Laundry</h5>
				</div>
			</div>
			<div class="col-6 col-md-3">
				<div class="bg-white p-4 text-center rounded shadow-sm h-100">
					<i class="fas fa-parking fs-1 mb-3" style="color: #12123e;"></i>
					<h5>Parking space</h5>
				</div>
			</div>
		</div>
	</div>
</section>
<!--all reviews section-->
<section class="py-5" style="background-color: #f7f2eb;">
    <div class="container py-4">
	    <h2 class="display-5 text-center mb-5">Hear from Our Guests</h2>
		<div id="reviewCards" class="row">
		    @foreach (var review in Model.ReviewViewModel)
		    {
			    <div class="col-md-6 mb-4">
				    <div class="bg-white p-4 rounded shadow-sm h-100">
					    <div class="d-flex justify-content-between align-items-center mb-3">
						    <span>@review.CreatedAt</span>
						    <div class="text-warning">
							    <i class="fas fa-star"></i>
							    <i class="fas fa-star"></i>
							    <i class="fas fa-star"></i>
							    <i class="fas fa-star"></i>
							    <i class="fas fa-star-half-alt"></i>
						    </div>
					    </div>
					    <p>
						   @review.Comments
					    </p>
				    </div>
			    </div>
		    }
	    </div>
	    <div class="d-flex justify-content-center mt-4">
		    <button id="prevBtn" class="btn btn-sm btn-dark mx-2">
			    <i class="fas fa-chevron-left"></i>
		    </button>
		    <button id="nextBtn" class="btn btn-sm btn-dark mx-2">
			    <i class="fas fa-chevron-right"></i>
		    </button>
	    </div>

    </div>
</section>

<button type="button" id="showCheckOutModalButton" class="d-none" data-bs-toggle="modal" data-bs-target="#checkOutModal">
	Show Checkout
</button>

<div class="modal fade" id="checkOutModal" tabindex="-1" aria-labelledby="checkOutModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="checkOutModalLabel">Checkout is Required</h5>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>
			<div class="modal-body">
				<p>Please complete the checkout.</p>
			</div>
			<div class="modal-footer">
				<a asp-controller="CheckOut" asp-action="CheckOutForm" class="btn btn-primary">Proceed to Checkout</a>
				<a asp-controller="Home" asp-action="Index" class="btn btn-secondary">Cancel</a>
			</div>
		</div>
	</div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        @if (ViewBag.ShowCheckOutModal == true)
        {
	        <text>
            document.getElementById('showCheckOutModalButton').click();
            </text>
        }
    });


	/* --- pager for review cards ---------------------------------- */
	document.addEventListener('DOMContentLoaded', () => {

		const pageSize = 2;                             //
		const cards    = [...document.querySelectorAll('#reviewCards > .col-md-6')];
		const pages    = Math.ceil(cards.length / pageSize);
		let   page     = 0;                             // 0-based index

		const render = () => {
			cards.forEach((card, i) => {
				card.classList.toggle('d-none', Math.floor(i / pageSize) !== page);
			});
		};
		render();                                       // show first page

		document.getElementById('nextBtn').addEventListener('click', () => {
			page = (page + 1) % pages;                  // loop forward
			render();
		});
		document.getElementById('prevBtn').addEventListener('click', () => {
			page = (page - 1 + pages) % pages;          // loop backward
			render();
		});
	});

</script>